name: Build MSI Installer

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: yarn install

      - name: Build Frontend
        run: yarn run build

      - name: Build Tauri MSI
        env:
          TAURI_SIGNING_PRIVATE_KEY: ""
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""
        run: yarn tauri build

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Retrac-Installer
          path: src-tauri/target/release/bundle/msi/*.msi
